services:
  server:
    build: ./server
    ports:
      - 3001:3001
    env_file: ./server/.env
    enviroment:
      DOCKER_DB_HOST: db
      FILE_STORAGE_PATH: /opt/bucket
    volumes:
      - ./server:/opt/app
      - /home/erick/.local/state/cl_bucket:/opt/bucket
    container_name: classfeed_server
    restart: always
    depends_on:
      - db

  db:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=classfeed
    restart: always
    container_name: classfeed_db
    volumes:
      - classfeed-db:/var/lib/postgresql/data

volumes:
  classfeed-db:
