services:
  server:
    build: ./server
    ports:
      - 3001:3001
    environment:
      - SERVER_PORT=3001
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=classfeed
      - DB_HOST=db
      - JWT_SECRET=123456
    volumes:
      - ./server:/opt/app
      - /home/erick/.local/state/cl_bucket:/opt/bucket
    container_name: classfeed_server
    restart: always
    depends_on:
      - db

  db:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=classfeed
    restart: always
    container_name: classfeed_db
    volumes:
      - classfeed-db:/var/lib/postgresql/data

volumes:
  classfeed-db:
